### ISSUE TITLE
Add support for VSCode Exploration Builds

### ISSUE THREAD

**Issue by zahidislm** [nonoroazoro/vscode-syncing#50]
### Specifications

* OS Version: Linux Ubuntu 18.10 

* VSCode Version: 1.32.0 Insiders [Electron 4 Exploration Builds]

### Expected Behavior
Extension activates on startup and using any of the extension commands is expected work as usual.

### Actual Behavior
Extension fails to activate on startup and commands are not found upon using them.
Probably from not being able to identify exploration builds as valid Insider builds after v2.1.0

### Steps to Reproduce

1. Install Insider exploration build from: https://github.com/Microsoft/vscode/issues/61787
2. Install vscode-syncing from Marketplace
3. Attempt to use any command from extension (eg. syncing.uploadSettings)

### Logs

> [Extension Host] Activating extension 'nonoroazoro.syncing' failed: Cannot identify the VSCode version.. (at Object.showMessage (/usr/share/code-exploration/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:735:197))

> [Extension Host] Here is the error stack:  Error: Cannot identify the VSCode version.
    at new a (/home/zahidislm/.vscode-exploration/extensions/nonoroazoro.syncing-2.1.0/dist/extension.js:1:12958)
    at Function.create (/home/zahidislm/.vscode-exploration/extensions/nonoroazoro.syncing-2.1.0/dist/extension.js:1:13392)
    at new l (/home/zahidislm/.vscode-exploration/extensions/nonoroazoro.syncing-2.1.0/dist/extension.js:1:86657)
    at Function.create (/home/zahidislm/.vscode-exploration/extensions/nonoroazoro.syncing-2.1.0/dist/extension.js:1:86785)
    at /home/zahidislm/.vscode-exploration/extensions/nonoroazoro.syncing-2.1.0/dist/extension.js:7:17800
    at t.activate (/home/zahidislm/.vscode-exploration/extensions/nonoroazoro.syncing-2.1.0/dist/extension.js:7:17948)
    at Function.t._callActivateOptional (/usr/share/code-exploration/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:740:963)
    at Function.t._callActivate (/usr/share/code-exploration/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:740:634)
    at /usr/share/code-exploration/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:739:810 (at /usr/share/code-exploration/resources/app/

> Error: command 'syncing.uploadSettings' not found
    at Proxy.t._tryExecuteCommand (commandService.ts:59)
    at commandService.ts:52
    at process._tickCallback (internal/process/next_tick.js:68)

**Comment by nonoroazoro** [comment]
@zahidislm Sorry for the late reply, I'll look into it.

**Comment by nonoroazoro** [comment]
@zahidislm I've finished the patch and will release after testing.

**Comment by nonoroazoro** [comment]
@zahidislm A new version is released to bring the support.
