### ISSUE TITLE
Missing `locale.json` breaks ungracefully

### ISSUE THREAD

**Issue by JoseAlban** [nonoroazoro/vscode-syncing#67]
### Specifications

* OS Version: macos 10.14

* VSCode Version: 1.30.x

### Expected Behavior
Sync ignores missing file and proceed

### Actual Behavior

```
console.ts:134 [Extension Host] Syncing: Error loading VSCode settings file: locale.json.
Error: ENOENT: no such file or directory, open '/Users/jose.alban/Library/Application Support/VSCodium/User/locale.json' (at r._loadContent.e.map.e (/Users/jose.alban/.vscode-oss/extensions/nonoroazoro.syncing-2.1.6/dist/extension.js:28:265069))
t.log @ console.ts:134
t._logExtensionHostMessage @ extensionHost.ts:453
(anonymous) @ extensionHost.ts:244
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
console.ts:134 [Extension Host] The following VSCode settings are invalid and will be ignored: locale.json (at m.getSettings (/Users/jose.alban/.vscode-oss/extensions/nonoroazoro.syncing-2.1.6/dist/extension.js:28:262808))
t.log @ console.ts:134
t._logExtensionHostMessage @ extensionHost.ts:453
(anonymous) @ extensionHost.ts:244
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
```

Breaks because file doesn't exist

### Steps to Reproduce

1. don't have `locale.json`

1. try to upload settings

**Comment by nonoroazoro** [comment]
The error messages are expected, and they should not affect the synchronization.
